# _config.yml

# サイトの基本情報
title: るくみるのホームページ
description: 気ままに書いていきます。
url: "https://ruk3k.github.io"
baseurl: "/my-homepage"

# OGP画像のデフォルト
og_image: "/assets/images/hedgehogIcon.png"

# Twitterアカウント
twitter_username: ruk3k

# Jekyllの動作設定
theme: minima
timezone: Asia/Tokyo
permalink: /blog/:categories/:title/

# ビルドから除外するファイル/ディレクトリ
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
